### ISSUE TITLE
ValidSpaceNameValidatorDirective should allow underscore in the name (not to start with)

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/ngx-fabric8-wit#80]
![unspecified](https://cloud.githubusercontent.com/assets/1395710/25221106/3b255bb8-25b4-11e7-98d3-837e7c9cd0dc.png)
in here: https://github.com/fabric8-ui/ngx-fabric8-wit/blob/master/src/app/spaces/valid-space-name.directive.ts#L20

**Comment by joshuawilson** [comment]
@corinnekrych do you want to take this on?

**Comment by corinnekrych** [comment]
@joshuawilson yes!
